services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gainz:${GAINZ_VERSION:-latest}
    restart: always
    env_file:
      - .env
    environment:
      GAINZ_HOST: 0.0.0.0


